CREATE TABLE users(
   id serial PRIMARY KEY,
   name VARCHAR (50) UNIQUE NOT NULL,
   email VARCHAR (50) UNIQUE NOT NULL
);

CREATE TABLE foods(
   id serial PRIMARY KEY,
   name VARCHAR (50) UNIQUE NOT NULL,
   total INTEGER
);